import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// Suppress TypeScript error for side-effect CSS import when no d.ts is present
// @ts-ignore
import "./globals.css";
import { Provider } from "./provider";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "ClearPay - User App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className}`}>
        <Provider>
          <div className="w-screen min-h-screen ">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
